-- Add detailed_guidance column to essays table
ALTER TABLE essays
ADD COLUMN detailed_guidance JSONB DEFAULT NULL;

-- Add comment for documentation
COMMENT ON COLUMN essays.detailed_guidance IS 'Detailed personalized writing guidance generated by AI, including grammar improvements, coherence suggestions, task response depth analysis, and overall assessment';
